# Pycaret

## Requirements

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pycaret.classification import *
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('mode.chained_assignment',  None)

In [2]:
inputs = 'inputs'
outputs = 'outputs'

train = pd.read_csv(inputs + '/train.csv')
test = pd.read_csv(inputs + '/test.csv')
submission = pd.read_csv(outputs + '/sample_submission.csv')

In [3]:
train.columns

Index(['index', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       'Q11', 'Q12', 'Q13', 'Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19', 'Q20',
       'Q21', 'Q22', 'Q23', 'Q24', 'Q25', 'Q26', 'country', 'introelapse',
       'testelapse', 'surveyelapse', 'TIPI1', 'TIPI2', 'TIPI3', 'TIPI4',
       'TIPI5', 'TIPI6', 'TIPI7', 'TIPI8', 'TIPI9', 'TIPI10', 'VCL1', 'VCL2',
       'VCL3', 'VCL4', 'VCL5', 'VCL6', 'VCL7', 'VCL8', 'VCL9', 'VCL10',
       'VCL11', 'VCL12', 'VCL13', 'VCL14', 'VCL15', 'VCL16', 'education',
       'urban', 'gender', 'engnat', 'age', 'hand', 'religion', 'orientation',
       'voted', 'married', 'familysize', 'ASD', 'nerdiness'],
      dtype='object')

## Model

In [4]:
numberic_features = ['index', 'introelapse', 'testelapse', 'familysize', 'age']
clf = setup(data=train, target='nerdiness', numeric_features=numberic_features)

In [5]:
best_2 = compare_models(sort='AUC', n_select=2)

In [6]:
blended = blend_models(estimator_list=best_2, fold=5, method='soft')

In [7]:
final_model = finalize_model(blended)

In [8]:
predictions = predict_model(final_model, test, raw_score=True)

In [9]:
predictions

,index,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,...,hand,religion,orientation,voted,married,familysize,ASD,Label,Score_0,Score_1
0,0,4.0,4.0,3.0,5.0,5.0,5.0,3.0,5.0,4.0,...,1.0,4.0,4.0,1.0,1.0,3.0,2.0,0,0.855,0.145
1,1,4.0,5.0,4.0,4.0,5.0,4.0,5.0,5.0,5.0,...,1.0,1.0,5.0,2.0,1.0,5.0,2.0,1,0.285,0.715
2,2,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,...,1.0,4.0,5.0,2.0,1.0,3.0,2.0,1,0.260,0.740
3,3,5.0,4.0,3.0,4.0,5.0,4.0,5.0,4.0,4.0,...,1.0,2.0,2.0,2.0,1.0,3.0,2.0,1,0.465,0.535
4,4,5.0,5.0,5.0,5.0,5.0,3.0,5.0,5.0,5.0,...,1.0,4.0,5.0,2.0,1.0,2.0,2.0,1,0.085,0.915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35447,35447,4.0,5.0,5.0,3.0,3.0,4.0,5.0,5.0,4.0,...,3.0,10.0,4.0,2.0,1.0,3.0,2.0,1,0.115,0.885
35448,35448,5.0,5.0,5.0,5.0,5.0,4.0,5.0,3.0,5.0,...,3.0,2.0,5.0,2.0,1.0,2.0,2.0,1,0.300,0.700
35449,35449,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,1.0,1.0,5.0,1.0,1.0,2.0,2.0,1,0.065,0.935
35450,35450,5.0,5.0,4.0,5.0,5.0,1.0,5.0,1.0,5.0,...,1.0,12.0,1.0,2.0,1.0,NaN,2.0,0,0.810,0.190
35451,35451,5.0,5.0,4.0,5.0,2.0,4.0,3.0,5.0,4.0,...,2.0,NaN,2.0,2.0,1.0,1.0,2.0,1,0.405,0.595

In [10]:
submission['nerdiness'] = predictions['Score_1']

In [11]:
submission.to_csv(outputs + '/pycaret_submission.csv', index=False)